# This is a TOML document
# This document is a configuration file for rss2peertube mirror bot
# copy this file into the same directory and rename it "config.toml" and then modify config.toml as necessary.

# These are global configuration options, they apply to the bot as a whole and therefore all channels.
[global]
video_download_dir = "/path/to/download/directory/" # must be absolute path and user writable directory
use_pt_http_import = "false" # Peertube supports sending HTTP links to videos instead of downloading and uploading them. Use this option if you do not want to archive videos and have limited bandwidth. Setting this to true negates delete_videos as videos will not be downloaded, and disables transcoding.
use_pt_cli_import = "true" #Use the CLI to have PeerTube import videos directly
delete_videos = "true" # Delete videos and metadata after upload to peertube, lowercase string
poll_frequency = 180 # poll frequency in minutes
cli_dir = "/home/errhead/PeerTube/" # must be absolute path
duplicate_match_percent = 50 # percentage match of title to determine. a higher number will let more possible duplicates through
# For every channel, a new [channel.x] entry must be added in [channel] in sequential numerical order starting at 0
# All fields must have values.
[channel]
    [channel.0]
    name = "channel_name" # bot name of the channel, whatever you want but needs to be unique. "Luke-odysee"
    channel_url = "https://lbryfeed.melroy.org/channel/odysee/@Luke:7" # Odysee rss feed format
    peertube_instance = "https://peertube.url" # URL of peertube instance
    peertube_channel = "peertube_channel" # peertube channel handle to upload video to
    peertube_username = "user" # peertube username
    peertube_password = "password" # peertube password WARNING this file needs to be secure

    [channel.1]
    name = "channel_name" # name of the channel, whatever you want but needs to be unique. "Luke-youtube"
    channel_id = ""https://www.youtube.com/feeds/videos.xml?channel_id=UC2eYFnH61tmytImy1mTYvhA" " # YT format rss feed
    peertube_instance = "https://peertube.url" # URL of peertube instance
    peertube_channel = "peertube_channel" # peertube channel handle to upload video to
    peertube_username = "user" # peertube username
    peertube_password = "password" # peertube password WARNING this file needs to be secure

    [channel.2]
    name = "channel_name" # name of the channel, whatever you want but needs to be unique. "Luke-bitchute"
    channel_id = "https://www.bitchute.com/feeds/rss/channel/lukesmith/" # BitChute channel rss feed format
    peertube_instance = "https://peertube.url" # URL of peertube instance
    peertube_channel = "peertube_channel" # peertube channel handle to upload video to
    peertube_username = "user" # peertube username
    peertube_password = "password" # peertube password WARNING this file needs to be secure
